#spring
app:
    name: demo
    port: 7070
spring:
    profiles:
        include:
            - web
    datasource:
        name: default
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
        username: root
        password: 123456
        #druid相关配置
        druid:
            filters: stat
            #配置初始化大小/最小/最大
            initial-size: 1
            min-idle: 1
            max-active: 20
            #获取超时连接等待时间
            max-wait: 60000
            #间隔多久进行一次检测，检测需要关闭的空闲连接
            time-between-eviction-runs-millis: 60000
            #一个连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: 20
##### mybatis #####
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.magicfish.web.domain.entity
##### 重写配置 #####
overrides:
    #logging
    logging:
        level:
            root: INFO
    #springcloud config
    eureka:
        client:
            enabled: false
            fetch-registry: false
            register-with-eureka: false
    setting:
        api:
            enable-cors: true
        auth:
            enabled: false
        # session
        # 存储Sess的方式, 可选 redis, mongodb
        sess:
            storage-engine: mongodb
        site:
            title: Weroll Demo Application
